name: Pull Request Check
on: [pull_request]

jobs:
  unit-test:
    strategy:
      matrix:
        php_version: [7.4]
        phpunit_version: [5.7]
        include:
          - php_version: 8.0
            phpunit_version: 9.6.16
    name: Unit testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Composer dependencies
        uses: actions/cache@v3
        with:
          path: /tmp/composer-cache
          key: ${{ runner.os }}-${{ hashFiles('composer.lock') }}

      - name: Installing dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php_version }}

      - name: Running unit test
        uses: php-actions/phpunit@v3
        with:
          version: ${{ matrix.phpunit_version }}
          php_version: ${{ matrix.php_version }}
